### ISSUE TITLE
When deleted message log is deleted

### ISSUE THREAD

**Issue by mijantoSVK** [wacutils/wacutils#8]
When deleted message log is deleted it doesn˙t send log. But in terminal is error message: 

Ignoring exception in on_message_delete
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord.py-0.16.12-py3.5.egg/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "main1.py", line 43, in on_message_delete
    await client.send_message(channel, embed=embed)
  File "/usr/local/lib/python3.5/dist-packages/discord.py-0.16.12-py3.5.egg/discord/client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "/usr/local/lib/python3.5/dist-packages/discord.py-0.16.12-py3.5.egg/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400)

**Comment by wacutils** [comment]
The deleting function of the bot is only in arts local version of it. This code does not have the deleting function, and it wont have it later. I've already talked about this issue, and it seems to only be a network issue. A possible solution would be to catch the error it throws, and either output some tinier error, or retry sending the embed msg.
